---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /mnt/hddstorage/nextcloud_data:/data
    ports:
      - 8443:443
    restart: unless-stopped
    networks:
      - frontend
      - backend
    labels:
      - homepage.group=Applications
      - homepage.name=Nextcloud
      - homepage.icon=nextcloud.png
      - homepage.href=https://nextcloud.server.sigmondkukla.dev
      - homepage.description=that cereal sludge did me in
      - homepage.ping=https://nextcloud.server.sigmondkukla.dev
  
  mariadb:
    image: mariadb
    container_name: nextcloud-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    networks:
      - backend
 
networks:
  frontend:
    external: true
    name: nginxproxymanager
  backend:
    driver: bridge