---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./nextcloud_config:/config
      - /mnt/hddstorage/nextcloud/data:/data
    ports:
      - 1443:443
    restart: unless-stopped
    networks:
      - frontend
      - backend
    labels:
      - homepage.group=Applications
      - homepage.name=Nextcloud
      - homepage.icon=nextcloud.png
      - homepage.href=URL
      - homepage.description=DESCRIPTION
      - homepage.ping=URL
  
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

networks:
  frontend:
    external: true
    name: nginxproxymanager
  backend:
    driver: bridge
